Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -34,10 +34,28 @@ jobs:
             key: ${{ secrets.BASTION_KEY }}
             port: 22
             script: |
-              ssh -i ~/.ssh/private_ec2_key -o StrictHostKeyChecking=no ec2-user@${{ secrets.PRIVATE_EC2_IP }} << 'EOF'
+              set -e #Exits immediately if any command fails
+  
+              # cleaning out the app directory
+              ssh -i ~/.ssh/private_ec2_key -o StrictHostKeyChecking=no ***@*** "rm -rf /opt/app/*"
+
+              # Pull latest repo or clone if it doesn't exit
+              if [ -d ~/deploy ]; then
+                cd ~/deploy
+                git reset --hard
+                git clean -fd
+                git pull origin main
+              else
+                git clone https://github.com/ParkerB1/AWS-Private-Linux-VPC-Lab.git ~/deploy
+                cd ~/deploy
+              fi
+  
+              # Copy files to private EC2 via SSH from bastion
+              echo "Copying repo to private EC2..."
+              scp -i ~/.ssh/private_ec2_key -o StrictHostKeyChecking=no -r ./app.py ***@***:/opt/app
+  
+              # SSH into private ec2 and restart app
+              echo "Restarting app service on private EC2..."
+              ssh -i ~/.ssh/private_ec2_key -o StrictHostKeyChecking=no ***@*** << 'EOF'
                 sudo systemctl restart app.service
               EOF
-
-
-
-
